from __future__ import annotations

from .base import HarnessSignature, ImplementationProfile, profile
from .sources import (
    ANTHROPIC_FABLE,
    ANTHROPIC_MANAGED,
    ANTHROPIC_OPUS5,
    BROWSER_USE,
    MACU,
    MACU_PAPER,
    META_MUSE,
    META_MUSE_EVAL,
    OPENAI_GPT56_CARD,
    OPENAI_MULTI_AGENT,
    XAI_GROK420_CARD,
    XAI_MULTI_AGENT,
)


def _h(name: str, **options: object) -> HarnessSignature:
    return HarnessSignature.create(name, options)


_LOCAL_PROVIDERS = (
    "openai-responses",
    "openai-compatible-responses",
    "openai-compatible-chat",
    "anthropic-messages",
)


PROFILES: tuple[ImplementationProfile, ...] = (
    profile(
        application="browser",
        profile_id="openai-hosted-multi-agent-functions",
        title="OpenAI hosted multi-agent with client browser functions",
        artifact_kind="provider_protocol",
        fidelity="exact_public_protocol",
        runtime_owner="openai_hosted",
        harnesses=(_h("openai_hosted_multi_agent", max_concurrent_subagents=3),),
        providers=("openai-responses",),
        environment_types=("browser",),
        model_families=("GPT-5.6 Sol", "GPT-5.6 Terra", "GPT-5.6 Luna"),
        exact_components=(
            "responses_multi_agent=v1 request and HTTP continuation",
            "agent-attributed developer function calls",
            "shared tools and maximum concurrent subagents",
            "published root and subagent injected coordination instructions",
        ),
        unavailable_components=(
            "hosted scheduler source and independent observation that the service applied the published injected instructions",
            "WebSocket response.inject transport",
        ),
        sources=(OPENAI_MULTI_AGENT, OPENAI_GPT56_CARD),
    ),
    profile(
        application="browser",
        profile_id="openai-hosted-web-search",
        title="OpenAI hosted multi-agent with hosted web search",
        artifact_kind="provider_protocol",
        fidelity="exact_public_protocol",
        runtime_owner="openai_hosted",
        harnesses=(
            _h(
                "openai_hosted_multi_agent",
                max_concurrent_subagents=3,
                hosted_tools=["web_search"],
            ),
        ),
        providers=("openai-responses",),
        environment_types=("none",),
        model_families=("GPT-5.6 Sol", "GPT-5.6 Terra", "GPT-5.6 Luna"),
        exact_components=(
            "documented hosted multi-agent request",
            "documented web_search tool declaration",
            "published root and subagent injected coordination instructions",
        ),
        unavailable_components=(
            "hosted scheduler, search implementation, unpublished internal instructions, and independent observation of server-side prompt application",
        ),
        sources=(OPENAI_MULTI_AGENT, OPENAI_GPT56_CARD),
    ),
    profile(
        application="browser",
        profile_id="xai-hosted-web-research-4",
        title="xAI hosted four-agent web research",
        artifact_kind="provider_protocol",
        fidelity="exact_public_protocol",
        runtime_owner="xai_hosted",
        harnesses=(
            _h("xai_hosted_multi_agent", agent_count=4, hosted_tools=["web_search"]),
        ),
        providers=("xai-responses",),
        environment_types=("none",),
        model_families=("grok-4.20-multi-agent-0309",),
        exact_components=(
            "low-effort four-agent request boundary",
            "hosted web_search tool declaration and aggregate usage",
        ),
        unavailable_components=("server scheduler and plaintext child trajectories",),
        sources=(XAI_MULTI_AGENT, XAI_GROK420_CARD),
    ),
    profile(
        application="browser",
        profile_id="xai-hosted-web-research-16",
        title="xAI hosted sixteen-agent web research",
        artifact_kind="provider_protocol",
        fidelity="exact_public_protocol",
        runtime_owner="xai_hosted",
        harnesses=(
            _h("xai_hosted_multi_agent", agent_count=16, hosted_tools=["web_search"]),
        ),
        providers=("xai-responses",),
        environment_types=("none",),
        model_families=("grok-4.20-multi-agent-0309",),
        exact_components=(
            "high-effort sixteen-agent request boundary",
            "hosted web_search tool declaration and aggregate usage",
        ),
        unavailable_components=("server scheduler and plaintext child trajectories",),
        sources=(XAI_MULTI_AGENT, XAI_GROK420_CARD),
    ),
    profile(
        application="browser",
        profile_id="meta-muse-spark-1.1-orchestration",
        title="Meta Muse Spark 1.1 browser orchestration",
        artifact_kind="provider_protocol",
        fidelity="documented_gap",
        status="catalog_only",
        runtime_owner="meta_hosted",
        providers=(),
        environment_types=(),
        model_families=("Muse Spark 1.1",),
        exact_components=(
            "public description of main-agent planning and parallel delegation",
            "public description of native tool and computer-use capability",
        ),
        unavailable_components=(
            "public API scheduler controls, child traces, prompts, limits, and timing",
        ),
        sources=(META_MUSE, META_MUSE_EVAL),
    ),
    profile(
        application="browser",
        profile_id="browser-use-0.13.7-upstream",
        title="Pinned Browser-Use 0.13.7 Agent and Browser runtime",
        fidelity="upstream_runtime_adapter",
        runtime_owner="browser_use_upstream",
        harnesses=(_h("browser_use_upstream"),),
        providers=("browser-use-upstream",),
        environment_types=("none",),
        model_families=("models supported by Browser-Use 0.13.7 LLM wrappers",),
        exact_components=(
            "official Agent policy, prompts, history, Browser runtime, actions, and model loop",
            "official provider wrapper selected from the pinned source checkout",
            "clean immutable Git checkout and bounded JSON-stdin process boundary",
        ),
        unavailable_components=(
            "browser binary, Python dependency, model, and provider bit identity require caller pins",
            "TokenCost records are an observed lower bound and mutable pricing is intentionally not fetched",
            "the parallel-agents example remains a separate scheduling study rather than this single Agent session",
        ),
        sources=(BROWSER_USE,),
    ),
    profile(
        application="browser",
        profile_id="browser-use-parallel-pattern",
        title="Browser-Use parallel scheduling pattern",
        fidelity="source_matched_reimplementation",
        runtime_owner="scaffoldlab_local",
        harnesses=(_h("flat_parallel", max_agents=8),),
        providers=_LOCAL_PROVIDERS,
        environment_types=("browser",),
        model_families=("provider-selected tool-capable model",),
        exact_components=(
            "distinct tasks run concurrently without a selector",
            "separate browser context per logical agent",
        ),
        unavailable_components=(
            "Browser-Use Agent policy, prompts, history, actions, and Browser runtime",
        ),
        sources=(BROWSER_USE,),
    ),
    profile(
        application="browser",
        profile_id="macu-text-dag",
        title="MACU text-DAG subset with browser tools",
        fidelity="source_matched_reimplementation",
        runtime_owner="scaffoldlab_local",
        harnesses=(_h("macu_dynamic_dag", max_workers=4),),
        providers=_LOCAL_PROVIDERS,
        environment_types=("browser",),
        model_families=("provider-selected manager and worker model",),
        exact_components=("mutable validated DAG and asynchronous ready frontier",),
        unavailable_components=(
            "upstream prompts, CUA subprocesses, VM cloning, file handoffs, and evaluator",
        ),
        sources=(MACU_PAPER, MACU),
    ),
    profile(
        application="browser",
        profile_id="macu-upstream",
        title="Pinned released MACU web-navigation runtime",
        fidelity="upstream_runtime_adapter",
        runtime_owner="macu_upstream",
        harnesses=(_h("macu_upstream"),),
        providers=("macu-upstream",),
        environment_types=("none",),
        model_families=("GPT-5.4 CUA", "Qwen 3.6 CUA", "supported manager models"),
        exact_components=(
            "released prompts, graph validator, scheduler, replanning, CUA subprocesses",
            "released result and cost artifact ingestion",
        ),
        unavailable_components=(
            "benchmark parity for Online-Mind2Web, WebTailBench, Odysseys, or OSWorld; the adapter supplies a generic blank-start task",
            "bit identity unless checkout, dependencies, VM image, and model snapshots are pinned; released summary omits initial graph-generation usage",
        ),
        sources=(MACU, MACU_PAPER),
    ),
    profile(
        application="browser",
        profile_id="anthropic-managed-web-research",
        title="Anthropic Managed Agents hosted web research",
        artifact_kind="provider_protocol",
        fidelity="exact_public_protocol",
        runtime_owner="anthropic_hosted",
        harnesses=(_h("anthropic_managed_agents"),),
        providers=("anthropic-managed-agents",),
        environment_types=("none",),
        model_families=("model pinned on the Managed Agent version",),
        exact_components=(
            "managed session/event/aggregate-usage boundary",
            "resolved pinned coordinator snapshot, non-empty roster, and snapshot digest",
        ),
        unavailable_components=(
            "hosted scheduler, child event streams, and mutable remote environment definition",
            "application-specific remote tools and permissions are caller-provisioned rather than a checked-in web-research manifest",
        ),
        sources=(ANTHROPIC_MANAGED,),
    ),
    *tuple(
        profile(
            application="browser",
            profile_id=f"anthropic-fable5-team-{team_size}",
            title=f"Mythos 5 fixed {team_size}-agent team simulation",
            fidelity="topology_simulation",
            status="simulation",
            runtime_owner="scaffoldlab_local",
            harnesses=(_h("fixed_agent_team", team_size=team_size),),
            providers=_LOCAL_PROVIDERS,
            environment_types=("browser",),
            model_families=("Claude Mythos 5",),
            exact_components=("published team size, lead role, peer messaging shape",),
            unavailable_components=(
                "public 1M total-token limit per agent is not enforced; exact prompts, timing, compaction behavior, tool schemas, and checkout behavior are unavailable",
            ),
            sources=(ANTHROPIC_FABLE,),
        )
        for team_size in (3, 5, 10)
    ),
    profile(
        application="browser",
        profile_id="anthropic-fable5-blocking",
        title="Mythos 5 blocking orchestrator simulation",
        fidelity="topology_simulation",
        status="simulation",
        runtime_owner="scaffoldlab_local",
        harnesses=(_h("blocking_orchestrator", max_workers=4),),
        providers=_LOCAL_PROVIDERS,
        environment_types=("browser",),
        model_families=("Claude Mythos 5",),
        exact_components=("fresh workers and round barrier",),
        unavailable_components=(
            "four workers is local; public 200K worker context and 100K manager compaction are not enforced, and exact prompts are unavailable",
        ),
        sources=(ANTHROPIC_FABLE,),
    ),
    profile(
        application="browser",
        profile_id="anthropic-fable5-async-browsecomp",
        title="Mythos 5 async BrowseComp topology simulation",
        fidelity="topology_simulation",
        status="simulation",
        runtime_owner="scaffoldlab_local",
        harnesses=(
            _h(
                "async_subagents",
                max_concurrent_subagents=4,
                max_total_subagents=20,
            ),
        ),
        providers=_LOCAL_PROVIDERS,
        environment_types=("browser",),
        model_families=("Claude Mythos 5",),
        exact_components=("published asynchronous lead/worker topology",),
        unavailable_components=(
            "the card discloses no BrowseComp spawn cap; four/twenty are local controls; exact prompts, message timing, tools, and compaction are unavailable",
        ),
        sources=(ANTHROPIC_FABLE,),
    ),
    *tuple(
        profile(
            application="browser",
            profile_id=f"anthropic-opus5-team-{team_size}",
            title=f"Opus 5 fixed {team_size}-agent team simulation",
            fidelity="topology_simulation",
            status="simulation",
            runtime_owner="scaffoldlab_local",
            harnesses=(_h("fixed_agent_team", team_size=team_size),),
            providers=_LOCAL_PROVIDERS,
            environment_types=("browser",),
            model_families=("Claude Opus 5",),
            exact_components=("published team size and peer topology",),
            unavailable_components=(
                "public 1M total-token limit per agent is not enforced; unreleased effort configuration, prompts, tools, timing, and worktrees are unavailable",
            ),
            sources=(ANTHROPIC_OPUS5,),
        )
        for team_size in (5, 10)
    ),
    profile(
        application="browser",
        profile_id="anthropic-opus5-async",
        title="Opus 5 async-subagent topology simulation",
        fidelity="topology_simulation",
        status="simulation",
        runtime_owner="scaffoldlab_local",
        harnesses=(
            _h(
                "async_subagents",
                max_concurrent_subagents=10,
                max_total_subagents=100,
            ),
        ),
        providers=_LOCAL_PROVIDERS,
        environment_types=("browser",),
        model_families=("Claude Opus 5",),
        exact_components=("published asynchronous lead/worker topology",),
        unavailable_components=(
            "worker caps are local despite no disclosed async cap, and the public 1M total-token limit per agent is not enforced; exact prompts, tools, timing, and worktrees are unavailable",
        ),
        sources=(ANTHROPIC_OPUS5,),
    ),
    profile(
        application="browser",
        profile_id="anthropic-opus5-cowork-safety",
        title="Opus 5 Cowork browser-safety evaluation",
        artifact_kind="evaluation_environment",
        fidelity="documented_gap",
        status="catalog_only",
        runtime_owner="anthropic_closed",
        providers=(),
        environment_types=(),
        model_families=("Claude Opus 5",),
        exact_components=("high-level evaluation description only",),
        unavailable_components=(
            "129 environments, injections, checker, probes, classifier, and product harness",
        ),
        sources=(ANTHROPIC_OPUS5,),
    ),
)
