from __future__ import annotations

from .base import HarnessSignature, ImplementationProfile, profile
from .sources import (
    ANTHROPIC_FABLE,
    ANTHROPIC_MANAGED,
    ANTHROPIC_OPUS5,
    GROK_BUILD,
    MACU,
    META_ARE,
    META_MUSE,
    OPENAI_COMPUTER,
    OPENAI_MULTI_AGENT,
    OPENAI_SHELL,
    PLATOON_RAO_SNAPSHOT,
    PRIME_AGENT,
    RAO_PAPER,
    RLM,
    SWE_BENCH,
    XAI_MULTI_AGENT,
)


def _h(name: str, **options: object) -> HarnessSignature:
    return HarnessSignature.create(name, options)


_LOCAL_PROVIDERS = (
    "openai-responses",
    "openai-compatible-responses",
    "openai-compatible-chat",
    "anthropic-messages",
)


PROFILES: tuple[ImplementationProfile, ...] = (
    profile(
        application="swe",
        profile_id="single-agent-control",
        title="Single-agent SWE control",
        fidelity="controlled_baseline",
        runtime_owner="scaffoldlab_local",
        harnesses=(_h("single"),),
        providers=_LOCAL_PROVIDERS,
        environment_types=("swe",),
        model_families=("any compatible tool-calling model",),
        exact_components=("one model context with one isolated workspace",),
        unavailable_components=(),
        sources=(SWE_BENCH,),
    ),
    profile(
        application="swe",
        profile_id="parallel-best-of-3",
        title="Three-candidate SWE best-of-N with selector",
        fidelity="controlled_baseline",
        runtime_owner="scaffoldlab_local",
        harnesses=(_h("parallel_best_of_n", n=3),),
        providers=_LOCAL_PROVIDERS,
        environment_types=("swe",),
        model_families=("any compatible tool-calling model",),
        exact_components=("three independent candidates and explicit judge selection",),
        unavailable_components=(),
        sources=(SWE_BENCH,),
    ),
    profile(
        application="swe",
        profile_id="openai-hosted-multi-agent-shell",
        title="OpenAI hosted multi-agent with local shell and editor functions",
        artifact_kind="provider_protocol",
        fidelity="source_matched_reimplementation",
        runtime_owner="openai_hosted",
        harnesses=(_h("openai_hosted_multi_agent", max_concurrent_subagents=3),),
        providers=("openai-responses",),
        environment_types=("swe",),
        model_families=("GPT-5.6 Sol", "GPT-5.6 Terra", "GPT-5.6 Luna"),
        exact_components=(
            "responses_multi_agent=v1 request and developer-tool continuation",
            "documented local shell call/output protocol when explicitly enabled",
        ),
        unavailable_components=(
            "hosted scheduler source, WebSocket transport, exact Codex product harness, and live-verified native-shell combination",
        ),
        sources=(OPENAI_MULTI_AGENT, OPENAI_SHELL),
    ),
    profile(
        application="swe",
        profile_id="openai-hosted-multi-agent-swe-computer",
        title="OpenAI hosted multi-agent SWE with computer-use tools",
        artifact_kind="provider_protocol",
        fidelity="source_matched_reimplementation",
        runtime_owner="openai_hosted",
        harnesses=(_h("openai_hosted_multi_agent", max_concurrent_subagents=3),),
        providers=("openai-responses",),
        environment_types=("swe_computer",),
        model_families=("GPT-5.6 Sol", "GPT-5.6 Terra", "GPT-5.6 Luna"),
        exact_components=(
            "documented multi-agent and computer client protocols",
            "SWE functions and computer tool shared across hosted agents",
        ),
        unavailable_components=(
            "hosted scheduler, exact Codex product harness, and a published or live-verified combined SWE/computer contract",
        ),
        sources=(OPENAI_MULTI_AGENT, OPENAI_COMPUTER, OPENAI_SHELL),
    ),
    profile(
        application="swe",
        profile_id="anthropic-managed-agents",
        title="Anthropic Managed Agents hosted SWE boundary",
        artifact_kind="provider_protocol",
        fidelity="exact_public_protocol",
        runtime_owner="anthropic_hosted",
        harnesses=(_h("anthropic_managed_agents"),),
        providers=("anthropic-managed-agents",),
        environment_types=("none",),
        model_families=("model pinned on the Managed Agent version",),
        exact_components=(
            "managed session, primary-event-list, cleanup, and aggregate-usage boundary",
            "resolved pinned coordinator snapshot, non-empty roster, and snapshot digest",
        ),
        unavailable_components=(
            "hosted scheduler, child event streams, and mutable remote environment definition",
            "application-specific remote tools and permissions are caller-provisioned rather than a checked-in SWE manifest",
        ),
        sources=(ANTHROPIC_MANAGED,),
    ),
    profile(
        application="swe",
        profile_id="meta-muse-spark-1.1-coding-orchestration",
        title="Meta Muse Spark 1.1 coding orchestration",
        artifact_kind="provider_protocol",
        fidelity="documented_gap",
        status="catalog_only",
        runtime_owner="meta_hosted",
        providers=(),
        environment_types=(),
        model_families=("Muse Spark 1.1",),
        exact_components=(
            "public main/subagent role, planning, escalation, and compaction description",
            "Meta ARE is separately identified as evaluation infrastructure",
        ),
        unavailable_components=(
            "public scheduler endpoint, prompts, child protocol, worktrees, and limits",
        ),
        sources=(META_MUSE, META_ARE),
    ),
    profile(
        application="swe",
        profile_id="prime-agent-0.7.1",
        title="Prime Agent 0.7.1 JSON v3 runtime protocol",
        artifact_kind="runtime_protocol",
        fidelity="exact_public_protocol",
        runtime_owner="prime_agent_upstream",
        harnesses=(_h("prime_agent"),),
        providers=("prime-agent",),
        environment_types=("none",),
        model_families=("Prime Agent supported providers and models",),
        exact_components=(
            "documented JSON v3 session/event framing and terminal agent_end contract",
            "mandatory 0.7.1 version check, no-session invocation, and caller-isolated workspace",
        ),
        unavailable_components=(
            "installed executable/package identity unless the optional executable SHA is pinned",
            "runtime internals, complete child-tree usage, security sandboxing, and cross-invocation daemon/session/continual state",
        ),
        sources=(PRIME_AGENT,),
    ),
    profile(
        application="swe",
        profile_id="grok-build-1.0.0",
        title="xAI Grok Build 1.0.0 headless runtime protocol",
        artifact_kind="runtime_protocol",
        fidelity="exact_public_protocol",
        runtime_owner="grok_build_upstream",
        harnesses=(_h("grok_build"),),
        providers=("grok-build",),
        environment_types=("none",),
        model_families=("Grok models supported by Grok Build 1.0.0",),
        exact_components=(
            "documented headless JSON invocation and result boundary",
            "mandatory 1.0.0 version check, explicit sandbox policy, and caller-isolated workspace",
        ),
        unavailable_components=(
            "installed npm/executable identity unless the optional executable SHA is pinned; npm/source revisions disagree",
            "scheduler internals and some compaction, side-model, or unfinished-child usage",
        ),
        sources=(GROK_BUILD,),
    ),
    profile(
        application="swe",
        profile_id="rlm-0.1.3-contract",
        title="RLM 0.1.3 external-context inference contract",
        fidelity="source_matched_reimplementation",
        runtime_owner="scaffoldlab_local",
        harnesses=(
            _h(
                "rlm_repl",
                max_iterations=16,
                max_subcalls=32,
                max_batch_size=8,
                max_concurrent_subcalls=4,
            ),
        ),
        providers=_LOCAL_PROVIDERS,
        environment_types=("swe",),
        model_families=("any compatible model; context-analysis path",),
        exact_components=(
            "external context variable, persistent code loop, batched and recursive subcalls",
            "shared Scaffold Lab ledger and trace",
        ),
        unavailable_components=(
            "official prompts, unrestricted/local upstream REPL, compaction and upstream runtime",
            "domain tools are intentionally withheld from the RLM controller/subcalls",
        ),
        sources=(RLM,),
    ),
    profile(
        application="swe",
        profile_id="rlm-0.1.3-upstream",
        title="Pinned official RLM 0.1.3 inference runtime",
        fidelity="upstream_runtime_adapter",
        runtime_owner="rlm_upstream",
        harnesses=(_h("rlm_upstream"),),
        providers=("rlm-upstream",),
        environment_types=("none",),
        model_families=("models supported by the official RLM 0.1.3 clients",),
        exact_components=(
            "official prompts, selected upstream REPL, and direct/batched subcalls",
            "recursive child RLM control when configured with max_depth >= 2",
            "clean pinned checkout and bounded JSON-stdin process boundary",
        ),
        unavailable_components=(
            "Scaffold Lab SWE/browser/computer tools and SWE patch parity are intentionally absent",
            "recursive child UsageSummary values are not merged into the v0.1.3 root summary",
            "adapter Docker/1500-second defaults differ from the library local/no-timeout defaults",
            (
                "structured context, custom tools, compaction, persistence, alternate "
                "backends, and sampling/orchestrator options are not exposed"
            ),
            "dependency, Python, container image, and model bit identity require caller pins",
        ),
        sources=(RLM,),
    ),
    profile(
        application="swe",
        profile_id="platoon-recursive-inference",
        title="Platoon recursive CodeAct inference without RAO training",
        fidelity="inference_only_reimplementation",
        runtime_owner="scaffoldlab_local",
        harnesses=(
            _h(
                "platoon_recursive_inference",
                max_steps_per_agent=15,
                max_total_subagents=32,
                max_children_per_action=4,
                max_concurrent_subagents=4,
            ),
        ),
        providers=_LOCAL_PROVIDERS,
        environment_types=("swe",),
        model_families=("any compatible model; untrained inference control",),
        exact_components=("recursive sequential/parallel child-control shape",),
        unavailable_components=(
            "official IPython runtime, exact prompts, domain actions, and budget semantics",
            "public RAO training and reward code are not executed; no paper-trained checkpoint is identified",
        ),
        sources=(RAO_PAPER, PLATOON_RAO_SNAPSHOT),
    ),
    profile(
        application="swe",
        profile_id="rao-policy-training",
        title="RAO policy-training reproduction",
        artifact_kind="training_method",
        fidelity="documented_gap",
        status="catalog_only",
        runtime_owner="rao_training",
        providers=(),
        environment_types=(),
        model_families=("trained shared recursive policy",),
        exact_components=(
            "published shared-policy objective, node-local reward plus delegation bonus, root-group leave-one-out baseline, and inverse depth-frequency weighting",
            "pinned Platoon inference and Tinker/AReaL training pipelines, reward code, prompts, configs, and task assets",
        ),
        unavailable_components=(
            "no Scaffold Lab adapter executes the pinned upstream training or inference runtime",
            "no paper-trained checkpoint is identified in the paper or snapshot",
            "exact service, model, dataset, judge, tool, and compute snapshots require independent pins",
        ),
        sources=(RAO_PAPER, PLATOON_RAO_SNAPSHOT),
    ),
    profile(
        application="swe",
        profile_id="macu-swe-computer-experiment",
        title="MACU-inspired DAG with SWE and computer-use tools",
        fidelity="source_matched_reimplementation",
        runtime_owner="scaffoldlab_local",
        harnesses=(_h("macu_dynamic_dag", max_workers=4),),
        providers=("openai-responses", "anthropic-messages"),
        environment_types=("swe_computer",),
        model_families=("provider-selected manager and worker model",),
        exact_components=("mutable DAG and ready-frontier scheduling",),
        unavailable_components=(
            "MACU is a CUA artifact, not an SWE system-card harness; upstream VM/file runtime",
        ),
        sources=(MACU,),
    ),
    *tuple(
        profile(
            application="swe",
            profile_id=f"anthropic-fable5-team-{team_size}",
            title=f"Mythos 5 fixed {team_size}-agent coding simulation",
            fidelity="topology_simulation",
            status="simulation",
            runtime_owner="scaffoldlab_local",
            harnesses=(_h("fixed_agent_team", team_size=team_size),),
            providers=_LOCAL_PROVIDERS,
            environment_types=("swe",),
            model_families=("Claude Mythos 5",),
            exact_components=("published team size and peer/lead topology",),
            unavailable_components=(
                "public 1M total-token limit per agent is not enforced; exact prompts, message timing, and Git worktrees are unavailable",
            ),
            sources=(ANTHROPIC_FABLE,),
        )
        for team_size in (3, 5, 10)
    ),
    profile(
        application="swe",
        profile_id="anthropic-fable5-blocking",
        title="Mythos 5 blocking coding simulation",
        fidelity="topology_simulation",
        status="simulation",
        runtime_owner="scaffoldlab_local",
        harnesses=(_h("blocking_orchestrator", max_workers=4),),
        providers=_LOCAL_PROVIDERS,
        environment_types=("swe",),
        model_families=("Claude Mythos 5",),
        exact_components=("fresh workers and blocking round barrier",),
        unavailable_components=(
            "worker count is local; public 200K worker context and 100K manager compaction are not enforced, and exact prompts/worktrees are unavailable",
        ),
        sources=(ANTHROPIC_FABLE,),
    ),
    profile(
        application="swe",
        profile_id="anthropic-fable5-async-programbench",
        title="Mythos 5 async ProgramBench coding simulation",
        fidelity="topology_simulation",
        status="simulation",
        runtime_owner="scaffoldlab_local",
        harnesses=(
            _h(
                "async_subagents",
                max_concurrent_subagents=4,
                max_total_subagents=20,
            ),
        ),
        providers=_LOCAL_PROVIDERS,
        environment_types=("swe",),
        model_families=("Claude Mythos 5",),
        exact_components=(
            "published four-concurrent/twenty-total ProgramBench limits",
        ),
        unavailable_components=(
            "exact prompts, next-tool-result message timing, compaction, and worktrees",
        ),
        sources=(ANTHROPIC_FABLE,),
    ),
    *tuple(
        profile(
            application="swe",
            profile_id=f"anthropic-opus5-team-{team_size}",
            title=f"Opus 5 fixed {team_size}-agent coding simulation",
            fidelity="topology_simulation",
            status="simulation",
            runtime_owner="scaffoldlab_local",
            harnesses=(_h("fixed_agent_team", team_size=team_size),),
            providers=_LOCAL_PROVIDERS,
            environment_types=("swe",),
            model_families=("Claude Opus 5",),
            exact_components=("published team size and peer/lead topology",),
            unavailable_components=(
                "public 1M total-token limit per agent is not enforced; unreleased effort, exact prompts, timing, and Git worktrees are unavailable",
            ),
            sources=(ANTHROPIC_OPUS5,),
        )
        for team_size in (5, 10)
    ),
    profile(
        application="swe",
        profile_id="anthropic-opus5-async",
        title="Opus 5 async-subagent coding simulation",
        fidelity="topology_simulation",
        status="simulation",
        runtime_owner="scaffoldlab_local",
        harnesses=(
            _h(
                "async_subagents",
                max_concurrent_subagents=10,
                max_total_subagents=100,
            ),
        ),
        providers=_LOCAL_PROVIDERS,
        environment_types=("swe",),
        model_families=("Claude Opus 5",),
        exact_components=("published asynchronous lead/worker topology",),
        unavailable_components=(
            "worker caps are local despite no disclosed async cap, and the public 1M total-token limit per agent is not enforced; unreleased effort, prompts, timing, and worktrees are unavailable",
        ),
        sources=(ANTHROPIC_OPUS5,),
    ),
    profile(
        application="swe",
        profile_id="xai-hosted-multi-agent-tools",
        title="xAI hosted multi-agent SWE tools",
        artifact_kind="provider_protocol",
        fidelity="documented_gap",
        status="catalog_only",
        runtime_owner="xai_hosted",
        providers=(),
        environment_types=(),
        model_families=("grok-4.20-multi-agent-0309",),
        exact_components=("hosted team request and hosted research tools",),
        unavailable_components=(
            "client shell/editor continuation is not published or implemented",
        ),
        sources=(XAI_MULTI_AGENT,),
    ),
    profile(
        application="swe",
        profile_id="swe-bench-4.1.0",
        title="SWE-bench 4.1.0 evaluator",
        artifact_kind="evaluation_environment",
        fidelity="documented_gap",
        status="catalog_only",
        runtime_owner="swe_bench_upstream",
        providers=(),
        environment_types=(),
        model_families=("environment only; model-independent",),
        exact_components=("released dataset and Docker evaluator boundary",),
        unavailable_components=("pinned evaluator images are not bundled",),
        sources=(SWE_BENCH,),
    ),
)
